### ISSUE TITLE
Update versioneer

### ISSUE THREAD

**Issue by jamesjer** [matthew-brett/scriptrunner#1]
The Fedora project has started doing test builds with an alpha version of python 3.11, to catch problems as early as possible.  Scripttester fails to build because its version of versioneer.py is too old; it uses SafeConfigParser, which was deprecated in python 3.2 and has been removed entirely in python 3.11.  Newer versions of versioneer.py have fixed this.  Thank you!

**Comment by matthew-brett** [comment]
Thanks - done.
